---

- hosts: workers
  remote_user: certuser
  tasks: 

    - name: Install httpd package
      apt: 
        name: apache2
        state: present
        update_cache: no
      become: yes

    - name: Start httpd service
      service: 
        name: apache2
        state: started
      become: yes
